export enum GoogleLoginActionsEnum {
    APP_GOOGLE_LOGIN_FIREBASE_AUTHORIZE = '@@app_googleLogin/FIREBASE_AUTHORIZE',
    APP_GOOGLE_LOGIN_FIREBASE_UNAUTHORIZE = '@@app_googleLogin/FIREBASE_UNAUTHORIZE'
}