import {
    NAV_HEIGHT_MD,
    NAV_HEIGHT_LG,
    PAPER_PADDING_MAX_MD,
    PAPER_PADDING_MAX_LG
} from '@constantsStyles';

export const CONTENT_PADDING_TOP_LG = NAV_HEIGHT_LG;
export const CONTENT_PADDING_TOP_MD = NAV_HEIGHT_MD;
export const CONTENT_PADDING_MD = PAPER_PADDING_MAX_MD;
export const CONTENT_PADDING_LG = PAPER_PADDING_MAX_LG;
