import {
    NAV_HEIGHT,
    PAPER_PADDING_MAX_MD,
    PAPER_PADDING_MAX_LG
} from '@constantsStyles';

export const CONTENT_PADDING_TOP = NAV_HEIGHT;
export const CONTENT_PADDING_MD = PAPER_PADDING_MAX_MD;
export const CONTENT_PADDING_LG = PAPER_PADDING_MAX_LG;
