export enum invalidError {
    noSpaces = 'NO_SPACES',
    notEmpty = 'NOT_EMPTY',
    NO_SPACES = 'noSpaces',
    NOT_EMPTY = 'notEmpty',
    NOT_LONG = 'notLong',
    notLong = 'NOT_LONG',
    NOT_EMAIL = 'notEmail',
    notEmail = 'NOT_EMAIL',
    noDigit = 'NO_DIGIT',
    NO_DIGIT = 'noDigit',
    NO_SPECIALS = 'noSpecials',
    noSpecials = 'NO_SPECIALS',
    NO_MATCH = 'noMatch',
    noMatch = 'NO_MATCH',
};