language: node_js
node_js:
- 8.11.3
cache:
  bundler: true
  directories:
  - node_modules
script:
- npm run tsc
- npm run deploy
deploy:
  provider: heroku
  app: fast-coding
  api_key:
    -secure: quHwXgwg6CN+HCDdqSWiXRYr/xsCMyMNHpTtoA14ifJOMcT8zzRHaeb/fRuH7TFuRqCQagQGvuw4041a8mD+QqRPy8yv5p1X9QPfRR0NUgaUY8pp2eukJVgc/4ZOLrkehDw+7PzCGQF1/HqFa2Bat6uXXbz7gAW/KlSK2XVFJIi6jPTiMigd464KjpThN9AyspoCGxmYGTUjXrlxG9sbry9cQZbpcKWpggSnvZdFy1Fp0YnziMfwfnhW5t9vCXzBQ17/cG9mmoM0skQH4MhefhrEetOCMUhw249HD/tmxZ8KpJgCsmfUXSSlKMTRzAK5leY4sP3FpaJ9lWYsFNI9sHglG+OeI5ddlUPUkTa3jOZJM33oezrxgKgdZz9BOyG+Hyj2X+1eQOeSANNEdLcPkjHiAjN5AOYkzssm2rV3eesdZTvwetxHxdb2riTkhdU0CGywWjmjCELsF/ebKPn3smZdr08kI6tk7Wyz38VHpK3mA7fPKrSW30Ai5dDVMmAmetCtlx/iZatzE83cxa6kLpmoF1UPNlDq55GqbqSzqPTK1mdFjINNpY2HhddMo64RYJUfIemqL9K3O02IlORRzUfIj5GxP+SBSoWsbIZ2NHiOvuJz98cr2qPND7OSnpP1zUC0tZgAxBfCxrzXi2ViOUZxXhe3TTz+IEqZr+nZWHY=
  on:
    repo: ziomecka/fast-coding