language: node_js
node_js:
- 8.11.3
cache:
  bundler: true
  directories:
  - node_modules
script:
- npm run tsc
- npm run deploy
deploy:
  provider: heroku
  app: fast-coding
  on:
    repo: ziomecka/fast-coding
env:
  global:
    secure: EOigO9OH2ErznhwQvb6RDrIslbuAmyGS1bpgz+32hAysnaSAS35WZPt7rhiBF3F4HPF0XTjTg36AZegwNLdosK0ZRUMU+UKM+eHw2vab6OFYtdmXOFvUoQQl4Ws9RfIVyUuEGbNuJk4uiFPwTzjzhm56q6vXc9sh9umePA2g+5imw0yW92XMioPotjiAbbvxX4g2J834PIhF/MYawRmkPMOS7V4HH/1yyIwrU+xQ7lP94mfR0n7AkXaATB7XMN19EUOFRryGLiQdXeGJn4I9FarNc1Qd5KrejdqK5fonSwVRJ9CgJA/W3xeD+ebZwuVx6+w+PSFSR9R3Pa0X0dXqhGHgUWqMaTrN+XCL6vV8NirebZlrfQxLzxysvcOM0R9w3qcpiSUSzG1KcfUxYh1XTp49DPFTWhNetDw5ngTjvKv12mzCjjOdEZ87GFks6PYXZuyDwWsCdPsdYLTc8WXvv5JJP4PJK2npx1pB8QGZGdjrPDfMyHg101zTny9Mz9l5zjjAVBiQje9mUQU+K0AjYUGF6354WEM9014h+E3J7PKVUXgqwjr8rann+xRYYwVhefspiJxlcI4QK1XLERZju4aAPOUylFcI1bvvH+LpIQ3Y7lyMM94SlvgngdXSFQ0kEf3p/LHrBunul7sAX2pcDPSwkHBzOCVZ2t6yUbomyng=
