const path = require('path');
const APP_DIR = path.resolve(__dirname, '..', 'src');

module.exports = {
    app: `${APP_DIR}/index.tsx`,
    // app_appMenu: `${APP_DIR}/app/AppMenu/index.ts`,
    // app_buttonWithHint: `${APP_DIR}/app/ButtonWithHint/index.ts`,
    // app_changePasswordForm: `${APP_DIR}/app/ChangePasswordForm/index.ts`,
    // app_content: `${APP_DIR}/app/Content/index.ts`,
    // app_csr: `${APP_DIR}/app/CSR/index.ts`,
    // app_dialog: `${APP_DIR}/app/Dialog/index.ts`,
    // app_dragOverable: `${APP_DIR}/app/DragOverable/index.ts`,
    // app_email: `${APP_DIR}/app/Email/index.ts`,
    // // app_// form: `${APP_DIR}/app/Form/index.tsx`,
    // app_formHelperText: `${APP_DIR}/app/FormHelperText/index.ts`,
    // app_googleLogin: `${APP_DIR}/app/GoogleLogin/index.ts`,
    // app_keyboardListener: `${APP_DIR}/app/KeyboardListener/index.ts`,
    // // app_// localize: `${APP_DIR}/app/Localize/index.ts`,
    // // app_// localStorage: `${APP_DIR}/app/LocalStorage/index.ts`,
    // app_locationChange: `${APP_DIR}/app/LocationChange/index.ts`,
    // app_login: `${APP_DIR}/app/Login/index.ts`,
    // app_loginForm: `${APP_DIR}/app/LoginForm/index.ts`,
    // app_menuButton: `${APP_DIR}/app/MenuButton/index.ts`,
    // app_menuList: `${APP_DIR}/app/MenuList/index.ts`,
    // app_menuRulesHoc: `${APP_DIR}/app/MenuRulesHoc/index.ts`,
    // app_nav: `${APP_DIR}/app/Nav/index.ts`,
    // app_newPasswordForm: `${APP_DIR}/app/NewPasswordForm/index.ts`,
    // app_newUserForm: `${APP_DIR}/app/NewUserForm/index.ts`,
    // app_notDesktop: `${APP_DIR}/app/NotDesktop/index.ts`,
    // app_notification: `${APP_DIR}/app/Notification/index.ts`,
    // app_password: `${APP_DIR}/app/Password/index.ts`,
    // app_remindPasswordForm: `${APP_DIR}/app/RemindPasswordForm/index.ts`,
    // app_table: `${APP_DIR}/app/Table/index.tsx`,
    // app_user: `${APP_DIR}/app/User/index.ts`,
    // app_welcome: `${APP_DIR}/app/Welcome/index.ts`,
    // components_lesson: `${APP_DIR}/components/Lesson/index.ts`,
    // components_lessons: `${APP_DIR}/components/Lessons/index.ts`,
    // components_lessonsLoader: `${APP_DIR}/components/LessonsLoader/index.ts`,
    // components_textGenerator: `${APP_DIR}/components/TextGenerator/index.ts`,
    // // shared: `${APP_DIR}/components/shared/index.ts`,
    // theme: `${APP_DIR}/theme/index.ts`,
    // views_AppRouter: `${APP_DIR}/views/AppRouter/index.ts`,
    // views_ChangePassword: `${APP_DIR}/views/ChangePassword/index.tsx`,
    // views_Home: `${APP_DIR}/views/Home/index.ts`,
    // views_Lesson: `${APP_DIR}/views/Lesson/index.ts`,
    // views_Lessons: `${APP_DIR}/views/Lessons/index.ts`,
    // views_Login: `${APP_DIR}/views/Login/index.tsx`,
    // views_NewPassword: `${APP_DIR}/views/NewPassword/index.tsx`,
    // views_Newuser: `${APP_DIR}/views/Newuser/index.tsx`,
    // views_RemindPassword: `${APP_DIR}/views/RemindPassword/index.tsx`,
    // views_RouteAuth: `${APP_DIR}/views/RouteAuth/index.ts`,
    // app: `${APP_DIR}/index.tsx`
};