export enum PasswordTypes {
    APP_PASSWORD_SET_PASSWORD_CURRENT = '@@app_password/SET_PASSWORD_CURRENT',
    APP_PASSWORD_SET_PASSWORD_NEW = '@@app_password/SET_PASSWORD_NEW',
    APP_PASSWORD_SET_PASSWORD_CONFIRM = '@@app_password/SET_PASSWORD_CONFIRM'
};